# Generated by Django 4.2.30 on 2026-04-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0002_alter_course_id_alter_enrollment_id_alter_lesson_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="certificate_issued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("F", "F"),
                    ("I", "Incomplete"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="last_accessed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="progress",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Percent complete (0-100)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("dropped", "Dropped"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
